db:
  image: mysql:5.7
  volumes:
  - /home/ludwigpossie/coral-docker/mysqldata/:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: foobar
web:
  build: .
  ports:
    - '80:80'
  links:
    - db
